"""
业态分析画像 — 每种业态的选址偏好、互补业态、权重分配、决策逻辑
"""

BUSINESS_PROFILES = {
    # ===== 餐饮类 =====
    "小餐饮": {
        "label": "小餐饮",
        "category": "餐饮",
        "complementary": "写字楼、学校、公交站、住宅小区、便利店",
        "competitor_note": "同价位小吃快餐聚集可形成「小吃街」效应，但>15家/千㎡时需差异化",
        "cost_sensitivity": "极高 — 客单价低(15-35元)，房租占比需控制15%以内，超出则难以盈利",
        "traffic_priority": "步行人流决定生死，核心辐射500米，门口经过人流量是首要指标",
        "target_demographic": "上班族(25-40岁)、学生(15-22岁)、周边居民，注重便捷和性价比",
        "key_metrics": "500m内写字楼+学校数、公交站密度、步行道人流量、同品类饱和度",
        "rent_range": "30-80元/㎡/月",
        "weights": {
            "population_density": 0.20,
            "traffic_accessibility": 0.18,
            "traffic_flow": 0.18,
            "consumer_profile": 0.08,
            "competition": 0.15,
            "complementary_businesses": 0.08,
            "category_advantage": 0.08,
            "cost_estimate": 0.05,
        },
        "decision_logic": """
小餐饮核心逻辑：
- 500米半径内上班族+学生≥2000人 → 基础客群合格
- 门口日人流≥3000 → 及格，≥8000 → 优秀
- 同品类≤10家 → 蓝海，10-20家 → 可进入需差异化，>20家 → 红海谨慎
- 月租金>100元/㎡ → 小餐饮不建议
"""
    },
    "大餐饮": {
        "label": "大餐饮",
        "category": "餐饮",
        "complementary": "购物商场、酒店、停车场、银行、商务写字楼",
        "competitor_note": "大餐饮讲究品牌力和宴请场景，同类型>3家需评估差异化空间",
        "cost_sensitivity": "中 — 客单价中高(80-200元)，可承受较高租金但需稳定翻台率",
        "traffic_priority": "车流+停车便利度，辐射半径2-5公里，自驾可达性是关键",
        "target_demographic": "家庭聚餐、商务宴请、朋友聚会，30-55岁消费力中上群体",
        "key_metrics": "停车场数量、商场密度、周边酒店数、道路等级、3km内住宅区规模",
        "rent_range": "50-150元/㎡/月",
        "weights": {
            "population_density": 0.12,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.12,
            "consumer_profile": 0.12,
            "competition": 0.15,
            "complementary_businesses": 0.12,
            "category_advantage": 0.10,
            "cost_estimate": 0.12,
        },
        "decision_logic": """
大餐饮核心逻辑：
- 3km半径内常住人口≥5万 → 客群基础合格
- 停车位≥20个(含周边公共停车场) → 及格
- 同类型大餐饮≤2家 → 蓝海，3-5家 → 可进入，>5家 → 竞争激烈
- 周边有酒店(商务客源)+商场(休闲客源) → 加分
"""
    },
    "中餐": {
        "label": "中餐",
        "category": "餐饮",
        "complementary": "购物商场、酒店、写字楼、银行、停车场",
        "competitor_note": "中餐品类丰富，需关注同菜系竞争。差异化菜系可容忍更多竞品",
        "cost_sensitivity": "中 — 视定位而定，家常菜偏低、私房菜偏高",
        "traffic_priority": "车流+步行兼顾，1-3km辐射半径",
        "target_demographic": "全年龄段，以家庭和社交聚餐为主",
        "key_metrics": "商场密度、住宅区规模、同菜系竞品数、停车便利度",
        "rent_range": "40-120元/㎡/月",
        "weights": {
            "population_density": 0.15,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.13,
            "consumer_profile": 0.10,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.12,
            "cost_estimate": 0.10,
        },
        "decision_logic": "中餐需同时关注步行客流和自驾便利性，同菜系竞品≤3家為安全区"
    },
    "日餐": {
        "label": "日餐",
        "category": "餐饮",
        "complementary": "购物商场、写字楼、咖啡店、酒店、停车场",
        "competitor_note": "日料客单价偏高，同类型日料店>2家需注意市场容量",
        "cost_sensitivity": "中低 — 客单价较高(80-300元)，可承受中高租金",
        "traffic_priority": "商圈人流+自驾，位于中高端商圈或写字楼集中区",
        "target_demographic": "25-45岁白领、情侣、商务人士，注重品质和环境",
        "key_metrics": "写字楼密度、商场档次、周边咖啡店数量（代表白领消费力）",
        "rent_range": "60-180元/㎡/月",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.10,
            "consumer_profile": 0.18,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.12,
            "cost_estimate": 0.10,
        },
        "decision_logic": "日餐核心竞争力是品质感和差异化，消费人群画像(白领占比)权重最高"
    },
    "西餐": {
        "label": "西餐",
        "category": "餐饮",
        "complementary": "购物商场、酒店、咖啡店、酒吧、停车场",
        "competitor_note": "西餐品类跨度大(快餐→正餐)，需按自身定位判断",
        "cost_sensitivity": "中低 — 正餐客单价较高",
        "traffic_priority": "中高端商圈、酒店集中区、外籍人士聚集区",
        "target_demographic": "25-45岁，有一定消费力和西餐接受度的人群",
        "key_metrics": "酒店数量、咖啡店密度、商场档次",
        "rent_range": "60-200元/㎡/月",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.10,
            "consumer_profile": 0.18,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.12,
            "cost_estimate": 0.10,
        },
        "decision_logic": "西餐选址关键是消费人群匹配度，周边酒店/咖啡店密度反映西餐消费意愿"
    },
    "火锅店": {
        "label": "火锅店",
        "category": "餐饮",
        "complementary": "购物商场、KTV、酒吧、停车场、住宅区",
        "competitor_note": "火锅是高频社交餐饮，同品类聚集可形成火锅一条街，但需差异化锅底/定位",
        "cost_sensitivity": "中 — 面积需求大(200-400㎡)，总租金压力不小",
        "traffic_priority": "商圈人流+停车，晚间客流占比高",
        "target_demographic": "18-40岁为主，朋友聚会、家庭聚餐场景",
        "key_metrics": "夜间商业活跃度、周边娱乐场所(KTV/酒吧)、停车便利度",
        "rent_range": "40-100元/㎡/月",
        "weights": {
            "population_density": 0.12,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.12,
            "consumer_profile": 0.12,
            "competition": 0.18,
            "complementary_businesses": 0.10,
            "category_advantage": 0.10,
            "cost_estimate": 0.11,
        },
        "decision_logic": "火锅店竞品权重最高(18%)，关注夜间经济和娱乐配套，面积大需控制总租金"
    },
    "烧烤店": {
        "label": "烧烤店",
        "category": "餐饮",
        "complementary": "酒吧、KTV、住宅区、夜市、停车场",
        "competitor_note": "烧烤有强聚集效应，同行多反而是好事(烧烤一条街)",
        "cost_sensitivity": "中高 — 翻台率低(就餐时间长)，需控制租金",
        "traffic_priority": "晚间人流密集区，夜生活商圈或大型住宅区周边",
        "target_demographic": "18-35岁年轻人为主，夜宵场景",
        "key_metrics": "夜间商业活跃度、酒吧/KTV数量、周边年轻人居住密度",
        "rent_range": "30-80元/㎡/月",
        "weights": {
            "population_density": 0.15,
            "traffic_accessibility": 0.10,
            "traffic_flow": 0.15,
            "consumer_profile": 0.12,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.10,
            "cost_estimate": 0.13,
        },
        "decision_logic": "烧烤店晚上是黄金时段，选址要关注夜生活氛围和年轻人聚集度"
    },
    "小吃店": {
        "label": "小吃店",
        "category": "餐饮",
        "complementary": "学校、公交站、住宅小区、写字楼、市场",
        "competitor_note": "小吃店可聚集形成美食街，>20家同类反而是优势(目的地效应)",
        "cost_sensitivity": "极高 — 客单价<20元，必须极小面积+高人流量才可持续",
        "traffic_priority": "步行人流，200m核心圈，截流位置(路口/公交站旁)最佳",
        "target_demographic": "全年龄段，注重便捷和实惠",
        "key_metrics": "步行道人流、公交站距离、200m内学校/住宅数量",
        "rent_range": "20-60元/㎡/月",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.25,
            "traffic_flow": 0.25,
            "consumer_profile": 0.05,
            "competition": 0.12,
            "complementary_businesses": 0.08,
            "category_advantage": 0.05,
            "cost_estimate": 0.10,
        },
        "decision_logic": "小吃店交通和人流权重最高(50%)，位置决定生死，找截流点而非目的地"
    },
    "烘焙店": {
        "label": "烘焙店",
        "category": "餐饮",
        "complementary": "住宅小区、学校、写字楼、咖啡店、超市",
        "competitor_note": "烘焙属高频低客单消费，500m内>3家同类需要差异化品类",
        "cost_sensitivity": "中高 — 需要展示空间，面积50-100㎡，控制租金占比",
        "traffic_priority": "社区底商最佳，上下班/上下学必经之路",
        "target_demographic": "家庭主妇、上班族、学生家长，注重新鲜和健康",
        "key_metrics": "500m内住宅户数、学校数量、写字楼数量、早晚高峰人流",
        "rent_range": "40-100元/㎡/月",
        "weights": {
            "population_density": 0.22,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.15,
            "consumer_profile": 0.10,
            "competition": 0.12,
            "complementary_businesses": 0.08,
            "category_advantage": 0.10,
            "cost_estimate": 0.08,
        },
        "decision_logic": "烘焙店人口密度权重最高(22%)，社区门口的刚需消费，早餐+下午茶双高峰"
    },
    "快餐店": {
        "label": "快餐店",
        "category": "餐饮",
        "complementary": "写字楼、学校、医院、公交站、便利店",
        "competitor_note": "快餐品牌效应强，知名连锁可带动客流但也加剧竞争",
        "cost_sensitivity": "中 — 翻台率极高，可承受中高租金",
        "traffic_priority": "步行人流，300米核心圈，写字楼/学校门口最佳",
        "target_demographic": "上班族(午市)、学生、医院就诊人群",
        "key_metrics": "300m内写字楼员工数、学校师生数、午市峰值人流",
        "rent_range": "50-150元/㎡/月",
        "weights": {
            "population_density": 0.20,
            "traffic_accessibility": 0.18,
            "traffic_flow": 0.18,
            "consumer_profile": 0.08,
            "competition": 0.15,
            "complementary_businesses": 0.08,
            "category_advantage": 0.05,
            "cost_estimate": 0.08,
        },
        "decision_logic": "快餐靠量取胜，写字楼集中区午市能撑起全天70%营收，选址=选写字楼"
    },

    # ===== 茶饮咖啡类 =====
    "奶茶店": {
        "label": "奶茶店",
        "category": "茶饮咖啡",
        "complementary": "学校、写字楼、购物商场、公交站、小吃店",
        "competitor_note": "奶茶店高度聚集，>5家可形成茶饮街，但需强品牌或差异化",
        "cost_sensitivity": "中 — 面积小(15-40㎡)，总租金可控，但需高坪效",
        "traffic_priority": "步行人流，200米黄金圈，截流位置最优",
        "target_demographic": "15-30岁女性为主，学生和年轻白领",
        "key_metrics": "学校/大学数量、年轻女性人流、同类聚集度",
        "rent_range": "80-300元/㎡/月（面积小总价可控）",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.20,
            "traffic_flow": 0.22,
            "consumer_profile": 0.15,
            "competition": 0.15,
            "complementary_businesses": 0.05,
            "category_advantage": 0.08,
            "cost_estimate": 0.05,
        },
        "decision_logic": "奶茶店客流权重最高(42%)，位置=人流×年轻人占比，学校+写字楼双覆盖最佳"
    },
    "咖啡店": {
        "label": "咖啡店",
        "category": "茶饮咖啡",
        "complementary": "写字楼、购物商场、书店、酒店、银行",
        "competitor_note": "咖啡市场由连锁品牌主导，独立咖啡店需靠环境和特色差异化",
        "cost_sensitivity": "中 — 面积50-150㎡，需舒适空间，租金不低",
        "traffic_priority": "写字楼底商最佳，商务区核心位置",
        "target_demographic": "25-45岁白领、商务人士，注重氛围和品质",
        "key_metrics": "写字楼数量及档次、白领密度、周边咖啡/茶饮饱和度",
        "rent_range": "60-200元/㎡/月",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.10,
            "consumer_profile": 0.20,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.10,
            "cost_estimate": 0.10,
        },
        "decision_logic": "咖啡店消费者画像权重最高(20%)，写字楼白领是核心客群，商圈商务氛围决定成败"
    },
    "甜品店": {
        "label": "甜品店",
        "category": "茶饮咖啡",
        "complementary": "购物商场、奶茶店、电影院、学校、住宅区",
        "competitor_note": "甜品属冲动消费，同品类聚集有协同但>5家需谨慎",
        "cost_sensitivity": "中高 — 客单价中等，翻台率偏低",
        "traffic_priority": "商场内或社区底商，休闲消费场景",
        "target_demographic": "15-35岁女性、情侣、带孩家庭",
        "key_metrics": "商场客流、奶茶店密度(互补引流)、周边年轻女性密度",
        "rent_range": "50-150元/㎡/月",
        "weights": {
            "population_density": 0.12,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.15,
            "consumer_profile": 0.15,
            "competition": 0.12,
            "complementary_businesses": 0.13,
            "category_advantage": 0.10,
            "cost_estimate": 0.08,
        },
        "decision_logic": "甜品店互补业态权重较高(13%)，与奶茶/电影院形成休闲消费链"
    },
    "饮品店": {
        "label": "饮品店",
        "category": "茶饮咖啡",
        "complementary": "购物商场、学校、写字楼、小吃店、公交站",
        "competitor_note": "饮品品类宽(果汁/酸奶/茶饮)，需明确自身定位",
        "cost_sensitivity": "中 — 面积小，总租金可控",
        "traffic_priority": "步行人流密集区，200-500米辐射圈",
        "target_demographic": "15-35岁，注重健康/口感，女性为主",
        "key_metrics": "学校数、写字楼数、步行人流、同类密度",
        "rent_range": "60-250元/㎡/月",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.20,
            "traffic_flow": 0.22,
            "consumer_profile": 0.15,
            "competition": 0.13,
            "complementary_businesses": 0.05,
            "category_advantage": 0.10,
            "cost_estimate": 0.05,
        },
        "decision_logic": "饮品店与奶茶店逻辑相似，交通+客流权重最高"
    },

    # ===== 酒店住宿类 =====
    "酒店": {
        "label": "酒店",
        "category": "酒店住宿",
        "complementary": "交通枢纽(火车站/机场)、写字楼、购物商场、餐饮、旅游景点",
        "competitor_note": "酒店竞争看品牌+位置+价格带，同档次酒店>5家需谨慎",
        "cost_sensitivity": "低 — 投资回报周期长，更看重长期资产价值",
        "traffic_priority": "交通枢纽3km内、商务区核心、旅游目的地",
        "target_demographic": "商务旅客、旅游游客、会议团队",
        "key_metrics": "交通枢纽距离、写字楼密度、旅游景点、同档次酒店数",
        "rent_range": "20-60元/㎡/月（长租/自持为主）",
        "weights": {
            "population_density": 0.08,
            "traffic_accessibility": 0.22,
            "traffic_flow": 0.15,
            "consumer_profile": 0.12,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.10,
            "cost_estimate": 0.08,
        },
        "decision_logic": "酒店交通权重最高(22%)，位置决定客源结构(商务vs旅游)，3km覆盖关键交通节点"
    },
    "民宿": {
        "label": "民宿",
        "category": "酒店住宿",
        "complementary": "旅游景点、特色街区、餐饮、咖啡店、停车场",
        "competitor_note": "民宿讲究独特性和体验感，同区域>10家民宿需有强差异化",
        "cost_sensitivity": "高 — 体量小(5-15间)，需要控制运营成本",
        "traffic_priority": "旅游目的地或城市特色街区，依赖线上引流+口碑传播",
        "target_demographic": "年轻自由行游客、情侣、家庭出游",
        "key_metrics": "周边旅游景点/网红打卡点、特色餐饮密度、交通可达性",
        "rent_range": "15-50元/㎡/月",
        "weights": {
            "population_density": 0.05,
            "traffic_accessibility": 0.18,
            "traffic_flow": 0.12,
            "consumer_profile": 0.15,
            "competition": 0.15,
            "complementary_businesses": 0.15,
            "category_advantage": 0.10,
            "cost_estimate": 0.10,
        },
        "decision_logic": "民宿互补业态权重高(15%)，周边旅游/餐饮/打卡资源是核心竞争力"
    },
    "青年旅舍": {
        "label": "青年旅舍",
        "category": "酒店住宿",
        "complementary": "交通枢纽、旅游景点、酒吧、青年文化空间、便利店",
        "competitor_note": "青旅受众是背包客和穷游族，同城市青旅数反映旅游热度",
        "cost_sensitivity": "极高 — 床位价低(40-80元)，需严格控制租金和运营成本",
        "traffic_priority": "交通枢纽1km内最佳，旅游信息中心附近",
        "target_demographic": "18-30岁背包客、穷游学生、义工旅行者",
        "key_metrics": "交通枢纽距离、城市旅游热度、周边青年文化设施",
        "rent_range": "10-30元/㎡/月",
        "weights": {
            "population_density": 0.05,
            "traffic_accessibility": 0.25,
            "traffic_flow": 0.15,
            "consumer_profile": 0.12,
            "competition": 0.12,
            "complementary_businesses": 0.10,
            "category_advantage": 0.08,
            "cost_estimate": 0.13,
        },
        "decision_logic": "青旅交通权重最高(25%)，离车站/机场越近越好，背包客首选便捷位置"
    },

    # ===== 零售商业类 =====
    "零售店": {
        "label": "零售店",
        "category": "零售商业",
        "complementary": "住宅小区、写字楼、学校、餐饮、公交站",
        "competitor_note": "零售品类差异大，需按具体品类判断竞品环境",
        "cost_sensitivity": "中高 — 利润率薄，需控制租金占比",
        "traffic_priority": "社区底商或商圈临街，依赖周边常驻人口",
        "target_demographic": "周边居民和上班族，便捷性优先",
        "key_metrics": "500m内住宅户数、写字楼员工数、周边互补业态丰富度",
        "rent_range": "40-120元/㎡/月",
        "weights": {
            "population_density": 0.25,
            "traffic_accessibility": 0.12,
            "traffic_flow": 0.13,
            "consumer_profile": 0.10,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.10,
            "cost_estimate": 0.05,
        },
        "decision_logic": "零售店人口密度权重最高(25%)，社区常驻人口是稳定客源"
    },
    "便利店": {
        "label": "便利店",
        "category": "零售商业",
        "complementary": "住宅小区、写字楼、学校、公交站、医院",
        "competitor_note": "便利店品牌效应极强(711/罗森/全家)，独立便利店需找连锁空白区",
        "cost_sensitivity": "中 — 24h运营人力成本高，但面积小(50-100㎡)",
        "traffic_priority": "社区出入口、写字楼大堂、学校门口，24小时截流位置",
        "target_demographic": "周边居民(晚间)、上班族(白天)、学生(放学)",
        "key_metrics": "300m内住户数、写字楼员工数、24h人流量、连锁便利店覆盖盲区",
        "rent_range": "60-200元/㎡/月",
        "weights": {
            "population_density": 0.28,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.15,
            "consumer_profile": 0.05,
            "competition": 0.15,
            "complementary_businesses": 0.05,
            "category_advantage": 0.07,
            "cost_estimate": 0.10,
        },
        "decision_logic": "便利店人口密度权重最高(28%)，300m内足够住户是24h运营的基础"
    },
    "超市": {
        "label": "超市",
        "category": "零售商业",
        "complementary": "住宅小区、停车场、餐饮、公交站、银行",
        "competitor_note": "超市辐射范围大(1-3km)，同规模超市>2家需谨慎",
        "cost_sensitivity": "低 — 面积大(500-5000㎡)，长期租约，租金谈判空间大",
        "traffic_priority": "大型住宅区核心位置或社区商业中心，停车便利",
        "target_demographic": "周边1-3km居民，家庭采购为主",
        "key_metrics": "辐射范围内住宅户数、停车位数量、公交可达性、同规模竞品",
        "rent_range": "20-60元/㎡/月",
        "weights": {
            "population_density": 0.25,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.10,
            "consumer_profile": 0.12,
            "competition": 0.15,
            "complementary_businesses": 0.05,
            "category_advantage": 0.10,
            "cost_estimate": 0.08,
        },
        "decision_logic": "超市核心竞争力是覆盖人口基数，1km内≥1万户是基础门槛"
    },
    "服装店": {
        "label": "服装店",
        "category": "零售商业",
        "complementary": "购物商场、同类服装店、餐饮、美容美发、停车场",
        "competitor_note": "服装店有聚集效应(服装一条街/商场)，但需定位差异化",
        "cost_sensitivity": "中 — 需要展示空间，面积50-200㎡",
        "traffic_priority": "商圈临街或商场内，逛街人流是关键",
        "target_demographic": "按定位不同(女装/男装/童装)，以女性消费者为主",
        "key_metrics": "商圈档次、同类聚集度、逛街人流量、周边互补(餐饮/美发)",
        "rent_range": "60-300元/㎡/月",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.20,
            "consumer_profile": 0.15,
            "competition": 0.12,
            "complementary_businesses": 0.10,
            "category_advantage": 0.10,
            "cost_estimate": 0.08,
        },
        "decision_logic": "服装店客流权重高(20%)，逛街人流×消费力匹配是关键"
    },
    "数码店": {
        "label": "数码店",
        "category": "零售商业",
        "complementary": "写字楼、学校、购物商场、咖啡店、停车场",
        "competitor_note": "数码产品标准化程度高，价格竞争激烈，需品牌授权或服务差异化",
        "cost_sensitivity": "中 — 面积需求中等，可位于次核心位置",
        "traffic_priority": "数码商圈(集中市场)或写字楼/学校周边",
        "target_demographic": "18-40岁男性为主，学生和年轻上班族",
        "key_metrics": "数码商圈集中度、学校/写字楼数量、同品类门店数",
        "rent_range": "50-150元/㎡/月",
        "weights": {
            "population_density": 0.12,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.10,
            "consumer_profile": 0.15,
            "competition": 0.18,
            "complementary_businesses": 0.08,
            "category_advantage": 0.12,
            "cost_estimate": 0.10,
        },
        "decision_logic": "数码店竞品权重较高(18%)，数码商圈聚集效应明显，但也意味着激烈价格战"
    },
    "药店": {
        "label": "药店",
        "category": "零售商业",
        "complementary": "住宅小区、医院、诊所、超市、公交站",
        "competitor_note": "连锁药店(老百姓/大参林等)扩张凶猛，500m内>2家药店需谨慎",
        "cost_sensitivity": "中 — 刚需行业，现金流稳定，可承受中等租金",
        "traffic_priority": "社区底商，大型住宅区出入口最佳",
        "target_demographic": "周边居民，中老年为主，全年龄段覆盖",
        "key_metrics": "500m内住宅户数、周边医院/诊所数量、同品类药店数",
        "rent_range": "50-150元/㎡/月",
        "weights": {
            "population_density": 0.30,
            "traffic_accessibility": 0.10,
            "traffic_flow": 0.10,
            "consumer_profile": 0.08,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.07,
            "cost_estimate": 0.10,
        },
        "decision_logic": "药店人口密度权重最高(30%)，500m内覆盖足够常驻人口是第一要素"
    },

    # ===== 生活服务类 =====
    "美容美发": {
        "label": "美容美发",
        "category": "生活服务",
        "complementary": "住宅小区、写字楼、购物商场、服装店、咖啡店",
        "competitor_note": "美容美发是刚需高频，社区内>3家时需靠技术/环境差异化",
        "cost_sensitivity": "中 — 服务附加值高，可承受中等租金",
        "traffic_priority": "社区底商或写字楼商圈，便利性优先",
        "target_demographic": "女性为主，25-55岁，注重服务品质",
        "key_metrics": "周边女性人口密度、住宅户数、写字楼女性白领数",
        "rent_range": "50-150元/㎡/月",
        "weights": {
            "population_density": 0.25,
            "traffic_accessibility": 0.12,
            "traffic_flow": 0.10,
            "consumer_profile": 0.15,
            "competition": 0.15,
            "complementary_businesses": 0.08,
            "category_advantage": 0.08,
            "cost_estimate": 0.07,
        },
        "decision_logic": "美容美发人口权重高(25%)，社区女性人口基数决定客流天花板"
    },
    "健身房": {
        "label": "健身房",
        "category": "生活服务",
        "complementary": "住宅小区、写字楼、购物商场、停车场、餐饮",
        "competitor_note": "健身房辐射1-2km，同规模健身房>2家需评估差异化(价格/课程/设施)",
        "cost_sensitivity": "低 — 面积大(800-2000㎡)，通常签长租约，租金占比可控",
        "traffic_priority": "大型社区或商务区，停车便利，交通可达性好",
        "target_demographic": "22-45岁白领和社区居民，注重健康和形象",
        "key_metrics": "1km内住宅户数+写字楼员工数、停车场容量、同规模竞品",
        "rent_range": "15-40元/㎡/月",
        "weights": {
            "population_density": 0.20,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.10,
            "consumer_profile": 0.18,
            "competition": 0.12,
            "complementary_businesses": 0.08,
            "category_advantage": 0.10,
            "cost_estimate": 0.07,
        },
        "decision_logic": "健身房需评估人口基数+消费力，1km内年轻白领和改善型住宅居民是核心客群"
    },
    "教育培训": {
        "label": "教育培训",
        "category": "生活服务",
        "complementary": "学校、住宅小区、公交站、餐饮、书店",
        "competitor_note": "教培机构高度聚集(教育综合体)，但学科类受政策影响大",
        "cost_sensitivity": "中高 — 需要多间教室，面积需求大，租金压力不小",
        "traffic_priority": "学校周边500m内最佳，大型社区底商",
        "target_demographic": "K12学生家长为主，幼儿和成人培训为辅",
        "key_metrics": "周边学校数量及学生规模、住宅户数(有孩家庭)、同类机构密度",
        "rent_range": "30-80元/㎡/月",
        "weights": {
            "population_density": 0.15,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.10,
            "consumer_profile": 0.20,
            "competition": 0.15,
            "complementary_businesses": 0.08,
            "category_advantage": 0.07,
            "cost_estimate": 0.10,
        },
        "decision_logic": "教育培训消费者画像权重高(20%)，周边有孩家庭密度决定市场容量"
    },
    "宠物店": {
        "label": "宠物店",
        "category": "生活服务",
        "complementary": "住宅小区、宠物医院、公园、咖啡店、超市",
        "competitor_note": "宠物经济快速增长，500m内>2家同类需评估服务差异化",
        "cost_sensitivity": "中 — 面积50-150㎡，含洗护区，租金可控",
        "traffic_priority": "中高端社区底商，遛狗动线上最佳",
        "target_demographic": "养宠家庭，25-45岁，有一定消费力",
        "key_metrics": "周边养宠家庭密度(可从中高端住宅推断)、宠物医院数量、公园距离",
        "rent_range": "50-150元/㎡/月",
        "weights": {
            "population_density": 0.22,
            "traffic_accessibility": 0.10,
            "traffic_flow": 0.08,
            "consumer_profile": 0.20,
            "competition": 0.15,
            "complementary_businesses": 0.08,
            "category_advantage": 0.10,
            "cost_estimate": 0.07,
        },
        "decision_logic": "宠物店看人口密度+消费力，中高端住宅区养宠比例高，是首选"
    },
    "洗衣店": {
        "label": "洗衣店",
        "category": "生活服务",
        "complementary": "住宅小区、写字楼、酒店、便利店、公交站",
        "competitor_note": "洗衣店辐射300-500m，同小区>2家竞争激烈",
        "cost_sensitivity": "中高 — 面积30-80㎡，设备投入大，需控制固定成本",
        "traffic_priority": "社区底商，住宅区主出入口附近",
        "target_demographic": "周边居民和上班族，便捷性第一",
        "key_metrics": "500m内住宅户数、写字楼员工数、同品类门店数",
        "rent_range": "30-80元/㎡/月",
        "weights": {
            "population_density": 0.30,
            "traffic_accessibility": 0.12,
            "traffic_flow": 0.08,
            "consumer_profile": 0.10,
            "competition": 0.15,
            "complementary_businesses": 0.08,
            "category_advantage": 0.07,
            "cost_estimate": 0.10,
        },
        "decision_logic": "洗衣店是纯社区刚需，人口密度权重最高(30%)，覆盖住户数决定营收上限"
    },
    "诊所": {
        "label": "诊所",
        "category": "生活服务",
        "complementary": "住宅小区、药店、学校、公交站、停车场",
        "competitor_note": "诊所辐射500-1000m，同类型诊所>3家需注意饱和",
        "cost_sensitivity": "中低 — 刚需高频，现金流极稳定，可承受中高租金",
        "traffic_priority": "社区底商或临街，易于发现和到达",
        "target_demographic": "周边居民为主，全年龄段",
        "key_metrics": "500m内住宅户数、人口年龄结构、周边药房数量、同类型诊所数",
        "rent_range": "40-120元/㎡/月",
        "weights": {
            "population_density": 0.25,
            "traffic_accessibility": 0.12,
            "traffic_flow": 0.08,
            "consumer_profile": 0.10,
            "competition": 0.15,
            "complementary_businesses": 0.10,
            "category_advantage": 0.10,
            "cost_estimate": 0.10,
        },
        "decision_logic": "诊所人口密度权重高(25%)，覆盖足够人口+周边药房配套是基础"
    },

    # ===== 休闲娱乐类 =====
    "酒吧": {
        "label": "酒吧",
        "category": "休闲娱乐",
        "complementary": "KTV、餐厅、酒店、停车场、夜市",
        "competitor_note": "酒吧聚集可形成酒吧街，但>10家时竞争白热化",
        "cost_sensitivity": "中 — 晚间营业，面积100-300㎡，翻台率低",
        "traffic_priority": "夜间商业区或娱乐聚集区，晚间人流密度是关键",
        "target_demographic": "18-35岁年轻人，注重氛围和社交",
        "key_metrics": "周边夜生活活跃度、年轻人口密度、KTV/餐饮配套、夜间安全指数",
        "rent_range": "40-150元/㎡/月",
        "weights": {
            "population_density": 0.10,
            "traffic_accessibility": 0.12,
            "traffic_flow": 0.18,
            "consumer_profile": 0.18,
            "competition": 0.12,
            "complementary_businesses": 0.12,
            "category_advantage": 0.10,
            "cost_estimate": 0.08,
        },
        "decision_logic": "酒吧看夜间客流+年轻消费力，娱乐聚集区(酒吧街)品牌效应强但竞争也激烈"
    },
    "KTV": {
        "label": "KTV",
        "category": "休闲娱乐",
        "complementary": "餐饮、酒吧、购物商场、酒店、停车场",
        "competitor_note": "KTV面积大(1000-3000㎡)，同商圈>2家大型KTV需谨慎",
        "cost_sensitivity": "低 — 大场地长租约，更多看长期经营而非短期租金",
        "traffic_priority": "商圈或娱乐区，停车便利，夜间可达性好",
        "target_demographic": "18-40岁，朋友聚会、团建、家庭娱乐",
        "key_metrics": "商圈能级、停车位容量、周边餐饮/酒吧配套、年轻人口密度",
        "rent_range": "15-40元/㎡/月",
        "weights": {
            "population_density": 0.12,
            "traffic_accessibility": 0.15,
            "traffic_flow": 0.15,
            "consumer_profile": 0.15,
            "competition": 0.12,
            "complementary_businesses": 0.13,
            "category_advantage": 0.08,
            "cost_estimate": 0.10,
        },
        "decision_logic": "KTV互补业态权重较高(13%)，餐饮+酒吧+KTV形成夜间娱乐消费链"
    },
    "剧本杀": {
        "label": "剧本杀",
        "category": "休闲娱乐",
        "complementary": "餐饮、奶茶店、KTV、大学/写字楼、公交站",
        "competitor_note": "剧本杀行业波动大，同商圈>5家时淘汰率高",
        "cost_sensitivity": "中高 — 需要多个包间(150-300㎡)，装修投入大",
        "traffic_priority": "大学城或年轻商圈，交通便利即可，不需核心位置",
        "target_demographic": "18-30岁学生和年轻白领，社交需求驱动",
        "key_metrics": "周边大学/年轻白领密度、同类聚集度、线上平台评分格局",
        "rent_range": "20-60元/㎡/月",
        "weights": {
            "population_density": 0.15,
            "traffic_accessibility": 0.12,
            "traffic_flow": 0.12,
            "consumer_profile": 0.22,
            "competition": 0.15,
            "complementary_businesses": 0.08,
            "category_advantage": 0.08,
            "cost_estimate": 0.08,
        },
        "decision_logic": "剧本杀消费者画像权重最高(22%)，年轻人密度决定市场，大学城周边最佳"
    },
    "网吧": {
        "label": "网吧",
        "category": "休闲娱乐",
        "complementary": "学校、住宅区、快餐店、便利店、公交站",
        "competitor_note": "网吧行业在收缩，同商圈>2家需谨慎评估需求",
        "cost_sensitivity": "中 — 面积大(200-500㎡)，设备投入高",
        "traffic_priority": "大学/职校周边或城中村，不需核心商圈",
        "target_demographic": "16-30岁男性为主，学生和年轻务工人员",
        "key_metrics": "周边学校(大学/职校)数量、年轻男性密度、同品类门店数",
        "rent_range": "15-50元/㎡/月",
        "weights": {
            "population_density": 0.18,
            "traffic_accessibility": 0.10,
            "traffic_flow": 0.10,
            "consumer_profile": 0.22,
            "competition": 0.12,
            "complementary_businesses": 0.08,
            "category_advantage": 0.10,
            "cost_estimate": 0.10,
        },
        "decision_logic": "网吧消费者画像权重高(22%)，大学城/城中村年轻男性密集区是第一选择"
    },
    "台球厅": {
        "label": "台球厅",
        "category": "休闲娱乐",
        "complementary": "酒吧、快餐店、便利店、住宅区、公交站",
        "competitor_note": "台球厅近年回暖，同商圈>3家评估差异化(装修/赛事/社交)",
        "cost_sensitivity": "中高 — 面积需求大(300-800㎡)，但可选非核心位置",
        "traffic_priority": "社区商圈或大学周边，不需一线位置",
        "target_demographic": "18-40岁男性为主，社交休闲需求",
        "key_metrics": "周边年轻男性密度、同类门店数、互补(酒吧/快餐)配套",
        "rent_range": "15-40元/㎡/月",
        "weights": {
            "population_density": 0.18,
            "traffic_accessibility": 0.12,
            "traffic_flow": 0.10,
            "consumer_profile": 0.22,
            "competition": 0.10,
            "complementary_businesses": 0.10,
            "category_advantage": 0.08,
            "cost_estimate": 0.10,
        },
        "decision_logic": "台球厅可选次核心位置(租金低)，但必须有足够年轻男性客群覆盖"
    },
}
